### PR TITLE
change Tub.listenOn() to require unicode type

### PR DESCRIPTION
**Pull request by zooko**
fixes https://github.com/warner/foolscap/issues/19

(Note: no accomodation is made in this patch for backward-compatibility of
client software that expects Tub.listenOn() to work when given a str.)

### CODE REVIEW

**Comment by warner** [comment]
Hrm. I'm -1 on this, but (as has happened many times in the past, my old friend) I suspect you may manage to convince me of the rightness of your proposal :).

My rationale:

* it feels weird to me to ask people to write the `u` in `tub.listenOn(u"tcp:0")`
* that string is never going to allow anything fancy
* it's never going to include non-printable characters
* it's not intended to capture human names
* it's frequently machine-generated
* if python has a "simple" string type, this deserves to use it (of course python3's simplest string type is the unicode one, but Foolscap can't do py3 yet, and may still be blocked by Twisted's incomplete py3 support, so you might say we're living in a py2 aesthetical milieu, in which bytes are the simpler type).
* plus I'm hesitant to ask downstream developers to change their code to accomodate it (I'm imagining the release notes now: "new features in version X.Y: gratuitous incompatibility!")

And, to be consistent, we should probably make FURLs unicode too, which means changing `Tub.getReference`, some stuff surrounding furlfiles, maybe the wire format of reference identifiers.. I'm not sure where it would stop. Should every argument that might be printed be unicode?

Incidentally, the patch is a bit big.. `humanreadable` is a nice library, but overlaps with `foolscap.logging` a bit. Also there's a stray diff at the end of the patch.

**Comment by zooko** [comment]
> Incidentally, the patch is a bit big.. humanreadable is a nice library, but overlaps with foolscap.logging a bit.

It was a mistake to include that.

>  Also there's a stray diff at the end of the patch.

Another mistake.

**Comment by zooko** [comment]
>     that string is never going to allow anything fancy
>     it's never going to include non-printable characters
>     it's not intended to capture human names
>     it's frequently machine-generated

I think it is a mistake to think that str is for simple (i.e. ASCII) and unicode is for fancy (i.e., non-ASCII). Instead I think the rule should be: str is for binary bytes (i.e. in binary formats/protocols), unicode is for characters (including ASCII characters).

The reason this is a mistake is that the type of strings is contagious, and so the more general correct type is the right type. For example: the reason I'm looking at this is that there is a bug in Tahoe-LAFS trunk preventing a user from using Tahoe-LAFS on their system, because they have non-ASCII characters in their path. The simplest, most general fix for bugs like that is for Tahoe-LAFS to use unicodes exclusively (never strs) to manage configuration parameters. But, Tahoe-LAFS would then need to specifically convert the configuration parameters back to strs *if* the configuration parameters were being passed as arguments to foolscap.

If foolscap's API accepted unicodes as arguments, this wouldn't be an issue for Tahoe-LAFS.

Note that the contents of the configuration parameters being passed to Foolscap do not contain non-ASCII characters, just the contents of *other* configuration parameters. That's why I say that the most general correct type is better here even though we don't need to pass non-ASCII chars to this Foolscap API — it is so that other people's machinery doesn't have to be special-cased for your case.

>     if python has a "simple" string type, this deserves to use it (of course python3's simplest string type  is the unicode one, but Foolscap can't do py3 yet, and may still be blocked by Twisted's incomplete py3 support, so you might say we're living in a py2 aesthetical milieu, in which bytes are the simpler type).

Why are Python2 strs ("bytes") simpler than Python2 unicodes?

>     plus I'm hesitant to ask downstream developers to change their code to accomodate it (I'm imagining the release notes now: "new features in version X.Y: gratuitous incompatibility!")

This is a really good reason to reject this patch.

It would be possible, with a very small modification to this patch, for the Foolscap API to accept either strs or unicodes.
 
> And, to be consistent, we should probably make FURLs unicode too, which means changing Tub.getReference, some stuff surrounding furlfiles, maybe the wire format of reference identifiers.. I'm not sure where it would stop. Should every argument that might be printed be unicode?

Yes. Every argument that might be printed should be unicode.

**Comment by warner** [comment]
thanks to #48, this API (and most others) now accepts either bytes or text

**Pull request closed without merging**
