### PR TITLE
socks client plugin - please code review and merge?

### PR DESCRIPTION
**Pull request by david415**
I suspect this code can be merged but if not then please let me know in a code review what I can do to fix it up.

### CODE REVIEW

**Comment by warner** [comment]
Niece! Some thoughts:

* let's call it `SOCKS` instead of `SocksPlugin`: SOCKS is almost always capitalized in other contexts, we use the name "handler" in all the docs (even though the file itself is named `connection_plugins.py` .. we might change that some day), and the existing `DefaultTCP` handler doesn't have "plugin" or "handler" in the name (but it should be clear from the import statement: `from foolscap connection_plugins import DefaultTCP`). Hm, now I'm thinking we should rename the file to `handlers.py` before anybody starts depending upon the filename.
 * maybe `SOCKS5`? Does txsocksx do both 4 and 5, or just 5?
* I'm a little anxious about adding a hard dependency on `txsocksx`. How bad would it sound to put this in an `extra_requires=` instead? Like, upstream programs could use depend on `foolscap[socks]` (and later `foolscap[tor]`). There are multiple downsides, though:
  * the whole definition of `class SocksPlugin` would have to be conditional on a previous `try: import txsocksx; except ImportError: txsocksx = None` succeeding, which is a drag
  * we'd need to update `tox.ini` to install `txsocksx` so that tests could still exercse it (I'm ok with requiring the extras to run the tests)
* it'd be nice if we could build the proxy endpoint in the constructor, instead of carrying those arguments around for later. Endpoints are re-usable, but we don't get the reactor until `hint_to_endpoint` is called. Oh: what if the constructor just took the proxy_endpoint as its only argument? Is there any use-case where you'd want to use a non-TCP4 endpoint to get to your SOCKS server? (it would enable those). Also, we could add a convenience function that takes (host, port, reactor) and returns a SOCKS handler for you.
* the "unrecognized TCP hint" error message is a bit misleading, now that the handler doesn't actually insist on the hint being TCP. Maybe make it "unrecognized TCP-like hint"? (it might still be useful to suggest that the hint is expected to be TCP-like, in that SOCKS requires a hostname and a port). Maybe "unrecognized host:port hint"?
* how stable is the `txsocksx.test.util.FakeEndpoint` class? I don't usually import things from the test cases of other packages (and I don't usually think about downstream users when I rearrange my own tests). OTOH these are just tests: if something breaks, we'll see it quickly, and if the Foolscap tests break against some newer version of txsocksx, it shouldn't affect downstream users like Tahoe.
* the test should also exercise the regexp not matching, and throwing `InvalidHintError`
* the branch should be rebased to current master. It might be nice to trim things down a bit too (maybe squash the "oops" and pyflakes fixes), but I'm trying to not be too picky about things like that :).

**Comment by david415** [comment]
txsocksx can do SOCKS4,4a,5.

SOCKS4 proxies tcp to an ip/port, therefore the app will leak hostnames via dns resolver, which is fine if you happen to set "DNSPort 53" in your torrc and set your resolv.conf to 127.0.0.1

SOCKS4a and SOCKS5 can let the proxy host resolve the hostname. SOCKS5 supports UDP which we don't need but it also has user/pass authentication which tor uses to determine if it should build a new circuit or use an existing one.

I think we should make the SOCKS plugin support only SOCKS5. So I guess we should just call it SOCKS5. We can always create more plugins if we need to support a different version of the protocol.

yes i think we should allow arbitrary endpoints for connecting to the SOCKS proxy because for example tor recently added a unix domain socket which accepts SOCKS connections. so we at least should support TCP and unix domain sockets.

**Comment by david415** [comment]
Howdy. OK. 

- I've renamed the plugin class to SOCKS5

- made it accept a "proxy endpoint descriptor string" which means that the user can specify any type of endpoint as a way to connect to the SOCKS proxy host. This is exactly what we want... especially given that Tor has a Unix domain socket for connecting to the SOCKS port as well as TCP.

**Comment by warner** [comment]
Ok, next steps (sorry there are so many of them):

Tell me about the API choices: why accept an endpoint *descriptor* rather than a real endpoint? and why accept a factory? If we stick with that API, `__init__` should assert that you didn't give it both, and that the types are right (when I see `endpoint=` I assume it's an Endpoint instance, not a string). If we stick with the factory function, we should probably pass in the reactor when we call it.

(I'm guessing that we might not be able to instantiate an Endpoint at handler creation time because we don't have a reactor or something, but I'm having trouble imagining the case)

The simpler API, in my mind, would be for the `SOCKS5` constructor to just take a (real) Endpoint instead of everything else. But I bet I'm missing something.

Other items:

- [ ] remove `txsocksx` from setup.py `install_requires`: that induces a hard-dependency. (the `extras_require=` clause in setup.py is perfect)
- [ ] move `SOCKS5` and everything else that was added to `connection_plugins.py` into `src/foolscap/connections/socks.py`. (the `connections/` directory is new as of a few minutes ago).  `socks.py` should start with an unconditional `import txsocksx`. Applications which do `from foolscap.connections import socks` will be responsible for catching `ImportError` if they have not declared a dependency on `foolscap[socks]`.
- [ ] lower priority: use an underscore prefix for the internal attributes of `SOCKS5` (e.g. `self._proxy_endpoint = None` instead of `self.proxy_endpoint = None`), just a style I've been trying to move to in the rest of the code
- [ ] remove `PluginDependencyNotLoaded`, the responsibility for explaining how to get socks support will be moved up into applications (but feel free to keep the instructional text in a docstring or a comment or something)
- [ ] move the new tests into a new file (`test_connection_socks.py`), and do a guarded `from foolscap.connections import socks` at the beginning, like you did in the old `connection_plugins.py` (setting `socks` to None if it fails). If the import fails, set `.skip = "txsocksx not available"` on the test cases that need it
- [ ] add `txsocksx` to `tox.ini`'s "deps" section, so tests will exercise the new code
- [ ] add a `topfiles/242.change` text file with a couple of sentences about what the new feature is about: these files will get used to build the release notes (`NEWS`), and recording them as we go helps capture user-facing documentation while we still remember the details
- [ ] include `closes ticket:242` in the commit comments
- [ ] squash down to one commit, then rebase onto current master, and force-push onto this branch (or close this PR and open a new one with the new clean branch)
- [ ] watch for travis to pass, investigate and revisit if it fails


thanks!

**Comment by warner** [comment]
At @david415 's request, I'm rewriting this patch directly, so I'm going to close this PR. I'll close the upstream ticket ([foolscap#242](https://foolscap.lothar.com/trac/ticket/242)) when it's landed, hopefully in the next few days. Thanks for all the hard work!

**Pull request closed without merging**
